# Generated by Django 5.0.7 on 2024-07-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_compra_fecha_compra_alter_venta_fecha_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cc_cliente',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.PositiveIntegerField(unique=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.PositiveIntegerField(unique=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.PositiveIntegerField(unique=True, verbose_name='Telefono'),
        ),
    ]
