# Generated by Django 5.1.1 on 2024-09-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_venta_total_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='det_venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
