# Generated by Django 5.1.2 on 2024-10-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_cliente_tipo_documento_alter_cliente_cc_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50),
        ),
    ]
