# Generated by Django 5.1.2 on 2024-10-10 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_administrador_estado_categoria_estado_cliente_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='empleado',
        ),
    ]
