# Generated by Django 5.1.2 on 2024-10-10 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_venta_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='estado',
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad'),
        ),
    ]
