# Generated by Django 5.1.2 on 2024-10-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_producto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre'),
        ),
    ]
