# Generated by Django 5.0.6 on 2024-06-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('Id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('Apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('Telefono', models.CharField(max_length=10, unique=True, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleado',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('Id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('Id_presentacion', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Presentacion',
                'verbose_name_plural': 'Presentaciones',
                'db_table': 'Presentacion',
            },
        ),
    ]
