# Generated by Django 5.0.7 on 2024-07-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(max_length=10, unique=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.IntegerField(max_length=10, unique=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.IntegerField(max_length=10, unique=True, verbose_name='Telefono'),
        ),
    ]
