# Generated by Django 5.0.6 on 2024-06-14 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_venta_cc_cliente_alter_venta_id_empleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='fecha',
            new_name='fecha_venta',
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
