# Generated by Django 5.1 on 2024-08-28 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_administrador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
    ]
