# Generated by Django 5.1 on 2024-08-30 19:06

import app.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_administrador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nombres',
        ),
        migrations.AddField(
            model_name='empleado',
            name='conf_contrasena',
            field=models.CharField(default='', max_length=128, verbose_name='Confirmación de contraseña'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='contrasena',
            field=models.CharField(default=1, max_length=128, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Contraseña'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default=1, max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='numero_documento',
            field=models.PositiveIntegerField(default=1, unique=True, validators=[app.models.Empleado.validar_numero_documento], verbose_name='Número de documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PSP', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Empleado', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.PositiveIntegerField(verbose_name='Teléfono'),
        ),
    ]
