# Generated by Django 5.1 on 2024-09-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_empleado_apellidos_remove_empleado_nombres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
    ]
