# Generated by Django 5.1 on 2024-09-05 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_det_venta_price_det_venta_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='det_venta',
            old_name='price',
            new_name='precio',
        ),
    ]
