# Generated by Django 5.1.1 on 2024-09-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_det_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='producto',
        ),
    ]
