# Generated by Django 5.1.1 on 2024-10-07 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_producto_cantidad_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.presentacion'),
        ),
    ]
